
 CREATE TABLE RS_CITY_CATALOG (
    id int NOT NULL PRIMARY KEY,
    createdAt timestamp,
    name 		TEXT,
    idState		int
   
 	
);

INSERT INTO RS_CITY_CATALOG VALUES (0,CURRENT_DATE, 'Abasolo',0);
INSERT INTO RS_CITY_CATALOG VALUES (1,CURRENT_DATE, 'Agualeguas',0);
INSERT INTO RS_CITY_CATALOG VALUES (2,CURRENT_DATE, 'Allende',0);
INSERT INTO RS_CITY_CATALOG VALUES (3,CURRENT_DATE, 'Anahuac',0);
INSERT INTO RS_CITY_CATALOG VALUES (4,CURRENT_DATE, 'Apodaca',0);
INSERT INTO RS_CITY_CATALOG VALUES (5,CURRENT_DATE, 'Arramberri',0);
INSERT INTO RS_CITY_CATALOG VALUES (6,CURRENT_DATE, 'Bustamante',0);
INSERT INTO RS_CITY_CATALOG VALUES (7,CURRENT_DATE, 'Cadereyta Jimenez',0);
INSERT INTO RS_CITY_CATALOG VALUES (8,CURRENT_DATE, 'Cerralvo',0);
INSERT INTO RS_CITY_CATALOG VALUES (9,CURRENT_DATE, 'China',0);
INSERT INTO RS_CITY_CATALOG VALUES (10,CURRENT_DATE, 'Cienega de Flores',0);
INSERT INTO RS_CITY_CATALOG VALUES (11,CURRENT_DATE, 'Doctor Arroyo',0);
INSERT INTO RS_CITY_CATALOG VALUES (12,CURRENT_DATE, 'Doctor Coss',0);
INSERT INTO RS_CITY_CATALOG VALUES (13,CURRENT_DATE, 'Doctor Gonzales',0);
INSERT INTO RS_CITY_CATALOG VALUES (14,CURRENT_DATE, 'El Carmen',0);
INSERT INTO RS_CITY_CATALOG VALUES (15,CURRENT_DATE, 'Galeana',0);
INSERT INTO RS_CITY_CATALOG VALUES (16,CURRENT_DATE, 'Garcia',0);
INSERT INTO RS_CITY_CATALOG VALUES (17,CURRENT_DATE, 'General Bravo',0);
INSERT INTO RS_CITY_CATALOG VALUES (18,CURRENT_DATE, 'General Escobedo',0);
INSERT INTO RS_CITY_CATALOG VALUES (19,CURRENT_DATE, 'General Teran',0);
INSERT INTO RS_CITY_CATALOG VALUES (20,CURRENT_DATE, 'General Trevino',0);
INSERT INTO RS_CITY_CATALOG VALUES (21,CURRENT_DATE, 'General Zaragoza',0);
INSERT INTO RS_CITY_CATALOG VALUES (22,CURRENT_DATE, 'General Zuazua',0);
INSERT INTO RS_CITY_CATALOG VALUES (23,CURRENT_DATE, 'Guadalupe',0);
INSERT INTO RS_CITY_CATALOG VALUES (24,CURRENT_DATE, 'Hidalgo',0);
INSERT INTO RS_CITY_CATALOG VALUES (25,CURRENT_DATE, 'Higueras',0);
INSERT INTO RS_CITY_CATALOG VALUES (26,CURRENT_DATE, 'Hualahuises',0);
INSERT INTO RS_CITY_CATALOG VALUES (27,CURRENT_DATE, 'Iturbide',0);
INSERT INTO RS_CITY_CATALOG VALUES (28,CURRENT_DATE, 'Juarez',0);
INSERT INTO RS_CITY_CATALOG VALUES (29,CURRENT_DATE, 'Lampazos de Naranjo',0);
INSERT INTO RS_CITY_CATALOG VALUES (30,CURRENT_DATE, 'Linares',0);
INSERT INTO RS_CITY_CATALOG VALUES (31,CURRENT_DATE, 'Los Aldamas',0);
INSERT INTO RS_CITY_CATALOG VALUES (32,CURRENT_DATE, 'Los Herreras',0);
INSERT INTO RS_CITY_CATALOG VALUES (33,CURRENT_DATE, 'Los Ramones',0);
INSERT INTO RS_CITY_CATALOG VALUES (34,CURRENT_DATE, 'Marin',0);
INSERT INTO RS_CITY_CATALOG VALUES (35,CURRENT_DATE, 'Melchor Ocampo',0);
INSERT INTO RS_CITY_CATALOG VALUES (36,CURRENT_DATE, 'Mier y Noriega',0);
INSERT INTO RS_CITY_CATALOG VALUES (37,CURRENT_DATE, 'Mina',0);
INSERT INTO RS_CITY_CATALOG VALUES (38,CURRENT_DATE, 'Montemorelos',0);
INSERT INTO RS_CITY_CATALOG VALUES (39,CURRENT_DATE, 'Monterrey',0);
INSERT INTO RS_CITY_CATALOG VALUES (40,CURRENT_DATE, 'Paras',0);
INSERT INTO RS_CITY_CATALOG VALUES (41,CURRENT_DATE, 'Pesqueria',0);
INSERT INTO RS_CITY_CATALOG VALUES (42,CURRENT_DATE, 'Rayones',0);
INSERT INTO RS_CITY_CATALOG VALUES (43,CURRENT_DATE, 'Salinas HIdalgo',0);
INSERT INTO RS_CITY_CATALOG VALUES (44,CURRENT_DATE, 'Salinas Victoria',0);
INSERT INTO RS_CITY_CATALOG VALUES (45,CURRENT_DATE, 'San NIcolas de los Garza',0);
INSERT INTO RS_CITY_CATALOG VALUES (46,CURRENT_DATE, 'San Pedro Garza Garcia',0);
INSERT INTO RS_CITY_CATALOG VALUES (47,CURRENT_DATE, 'Santa Catarina',0);
INSERT INTO RS_CITY_CATALOG VALUES (48,CURRENT_DATE, 'Santiago',0);
INSERT INTO RS_CITY_CATALOG VALUES (49,CURRENT_DATE, 'Vallecillo',0);



/*
 * Role 0 admin
 * Role 1 user
 * status 0 inactive
 * status 1 active
 */