 CREATE TABLE BNB_PREFIX_ACTION_KEYWORD (
    ID SERIAL NOT NULL PRIMARY KEY,
    KEYWORD_NAME TEXT,
    action_id		INT,
    CREATED_DATE timestamp,
    LAST_UPDATE_DATE timestamp,
	CARRIER_ID		INT
   
); 