
 INSERT INTO BNB_SERVICE_SUB_KEYWORD(KEYWORD_NAME, CREATED_DATE, SERVICE_ID)
 VALUES('ef',now(),1);

  INSERT INTO BNB_SERVICE_SUB_KEYWORD(KEYWORD_NAME, CREATED_DATE, SERVICE_ID)
 VALUES('EF',now(),1);

 INSERT INTO BNB_SERVICE_SUB_KEYWORD(KEYWORD_NAME, CREATED_DATE, SERVICE_ID)
 VALUES('ك م',now(),2);

 INSERT INTO BNB_SERVICE_SUB_KEYWORD(KEYWORD_NAME, CREATED_DATE, SERVICE_ID)
 VALUES( 'ك بيت',now(),3);

 INSERT INTO BNB_SERVICE_SUB_KEYWORD(KEYWORD_NAME, CREATED_DATE, SERVICE_ID)
 VALUES( 'KG',now(),4);

 INSERT INTO BNB_SERVICE_SUB_KEYWORD(KEYWORD_NAME, CREATED_DATE, SERVICE_ID)
 VALUES( 'ك ج',now(),5);

 INSERT INTO BNB_SERVICE_SUB_KEYWORD(KEYWORD_NAME, CREATED_DATE, SERVICE_ID)
 VALUES( 'GOAL',now(),6);

 INSERT INTO BNB_SERVICE_SUB_KEYWORD(KEYWORD_NAME, CREATED_DATE, SERVICE_ID)
 VALUES( 'PJ',now(),7);