
 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('SUB',1,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('SU B',1,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('S U B',1,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('S UB',1,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('UNSUB',2,now(),now(),1);


 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('UN SUB',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('UNS UB',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('UNSU B',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('U NSUB',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('U N SUB',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('U N S UB',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('U N S U B',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('USUB',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('U S U B',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('U SUB',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('US UB',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('USU B',2,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('HELP',3,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('H ELP',3,now(),now(),1);
 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('HE LP',3,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('HEL P',3,now(),now(),1);

 INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('H E L P',3,now(),now(),1);

  INSERT INTO BNB_PREFIX_ACTION_KEYWORD(KEYWORD_NAME, action_id, CREATED_DATE, LAST_UPDATE_DATE,CARRIER_ID)
 VALUES('H EL P',3,now(),now(),1);
